I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 320, in script
    irving "What are we craving tonight, darling?"
Exception: Sayer 'irving' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 320, in script
    irving "What are we craving tonight, darling?"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'irving' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Date Night Dress Up 1.0
Wed Apr 13 18:25:22 2022
